#BungeeEssentials config v0.0.6
chat: "[%server%] %customname% >> %chat%"
msg: "%sender_customname% >> %receiver_customname%: %chat%" 
customnameprefix: "~"
join-msg: "%customname%§a joined to proxy."
leave-msg: "%customname% §cleaved from proxy."
change-server-msg: "%customname% §bchanged server to %after%§b."
server-shortcuts:
- server: "lobby"
  command: "lobby"